//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqn_WebMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckEmail
    {
        public int Id { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string ActiveCode { get; set; }
        public string UserId { get; set; }
    
        public virtual CheckEmail CheckEmail1 { get; set; }
        public virtual CheckEmail CheckEmail2 { get; set; }
    }
}
