//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqn_WebMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidoFile
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FivPath { get; set; }
        public string Status { get; set; }
        public string FileExt { get; set; }
    }
}
